name: BeSoBAG4u
url: http://BeSoBAG4u.github.io
description: Besondere Taschen von Beat und Sonja.

permalink: /:year/:month/:day/:title/
paginate: 10
pygments: true

markdown: kramdown

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']
